name: Node.js CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: self-hosted  # Using a self-hosted runner instead of GitHub-hosted runner
    strategy:
      matrix:
        node-version: [20.x]  # Testing with Node.js 20.x only
    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'  # Caching npm dependencies
    - run: npm ci  # Install dependencies using npm ci
    - run: npm run build --if-present  # Run build script if it exists
    - run: |
        touch .env
        echo "${{ secrets.MONGO_DB_URL }}" > .env
        echo "${{ secrets.JESON_WEB_TOKEN }}" > .env
        echo "${{ secrets.PORT }}" > .env
